/* automatically generated by rust-bindgen 0.72.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ModuleInferCtx {
    pub _nn_module: *mut ::std::os::raw::c_void,
    pub batch_feature: *mut f32,
    pub batch_lengths: *mut ::std::os::raw::c_long,
    pub output: *mut f32,
    pub _stream: *mut ::std::os::raw::c_void,
    pub device_id: ::std::os::raw::c_int,
    pub _device: *mut ::std::os::raw::c_void,
    pub _batch_feature_tensor: *mut ::std::os::raw::c_void,
    pub _batch_lengths_tensor: *mut ::std::os::raw::c_void,
    pub _batch_feature_cuda_tensor: *mut ::std::os::raw::c_void,
    pub _batch_lengths_cuda_tensor: *mut ::std::os::raw::c_void,
    pub _output_tensor: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ModuleInferCtx"][::std::mem::size_of::<ModuleInferCtx>() - 96usize];
    ["Alignment of ModuleInferCtx"][::std::mem::align_of::<ModuleInferCtx>() - 8usize];
    ["Offset of field: ModuleInferCtx::_nn_module"]
        [::std::mem::offset_of!(ModuleInferCtx, _nn_module) - 0usize];
    ["Offset of field: ModuleInferCtx::batch_feature"]
        [::std::mem::offset_of!(ModuleInferCtx, batch_feature) - 8usize];
    ["Offset of field: ModuleInferCtx::batch_lengths"]
        [::std::mem::offset_of!(ModuleInferCtx, batch_lengths) - 16usize];
    ["Offset of field: ModuleInferCtx::output"]
        [::std::mem::offset_of!(ModuleInferCtx, output) - 24usize];
    ["Offset of field: ModuleInferCtx::_stream"]
        [::std::mem::offset_of!(ModuleInferCtx, _stream) - 32usize];
    ["Offset of field: ModuleInferCtx::device_id"]
        [::std::mem::offset_of!(ModuleInferCtx, device_id) - 40usize];
    ["Offset of field: ModuleInferCtx::_device"]
        [::std::mem::offset_of!(ModuleInferCtx, _device) - 48usize];
    ["Offset of field: ModuleInferCtx::_batch_feature_tensor"]
        [::std::mem::offset_of!(ModuleInferCtx, _batch_feature_tensor) - 56usize];
    ["Offset of field: ModuleInferCtx::_batch_lengths_tensor"]
        [::std::mem::offset_of!(ModuleInferCtx, _batch_lengths_tensor) - 64usize];
    ["Offset of field: ModuleInferCtx::_batch_feature_cuda_tensor"]
        [::std::mem::offset_of!(ModuleInferCtx, _batch_feature_cuda_tensor) - 72usize];
    ["Offset of field: ModuleInferCtx::_batch_lengths_cuda_tensor"]
        [::std::mem::offset_of!(ModuleInferCtx, _batch_lengths_cuda_tensor) - 80usize];
    ["Offset of field: ModuleInferCtx::_output_tensor"]
        [::std::mem::offset_of!(ModuleInferCtx, _output_tensor) - 88usize];
};
unsafe extern "C" {
    pub fn build_module_infer_ctx(
        model_path: *const ::std::os::raw::c_char,
        device_id: ::std::os::raw::c_int,
        batch: ::std::os::raw::c_int,
        tt: ::std::os::raw::c_int,
        feat_len: ::std::os::raw::c_int,
        output_size: ::std::os::raw::c_int,
        pin_memory: bool,
    ) -> ModuleInferCtx;
}
unsafe extern "C" {
    pub fn do_infer(ctx: *mut ModuleInferCtx);
}
unsafe extern "C" {
    pub fn free_module_infer_ctx(ctx: *mut ModuleInferCtx);
}
